version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: salon-db
    restart: always
    environment:
      POSTGRES_USER: salonuser
      POSTGRES_PASSWORD: salonpassword
      POSTGRES_DB: salondb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web-network

  app:
    build: .
    container_name: salon-app
    restart: always
    ports:
      - "3005:3000"
    environment:
      DATABASE_URL: "postgresql://salonuser:salonpassword@db:5432/salondb?schema=public"
      JWT_SECRET: "sua_chave_secreta_aqui"
      WAHA_API_URL: "http://waha:3000"
      NODE_ENV: production
    depends_on:
      - db
      - waha
    networks:
      - web-network

  waha:
    image: devlikeapro/waha
    container_name: salon-waha
    restart: always
    ports:
      - "3006:3000"
    environment:
      WHATSAPP_DEFAULT_SESSION: default
      WAHA_PRINT_QR: "true"
    networks:
      - web-network

volumes:
  postgres_data:

networks:
  web-network:
    name: dodile_web-network
    external: true
