services:
  db:
    image: postgres:15-alpine
    container_name: salon-db
    restart: always
    environment:
      POSTGRES_USER: salonuser
      POSTGRES_PASSWORD: salonpassword
      POSTGRES_DB: salondb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web-network
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build: .
    container_name: salon-app
    restart: always
    ports:
      - "3005:3000"
    environment:
      DATABASE_URL: "postgresql://salonuser:salonpassword@db:5432/salondb?schema=public"
      JWT_SECRET: "sua_chave_secreta_aqui"
      WAHA_API_URL: "http://waha:8080"
      WAHA_API_KEY: "waha_secret_key_2024"
      NODE_ENV: production
      ASAAS_API_KEY: ${ASAAS_API_KEY}
      ASAAS_API_URL: ${ASAAS_API_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      APP_URL: ${APP_URL}
    depends_on:
      - db
      - waha
    networks:
      - web-network
    deploy:
      resources:
        limits:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  waha:
    image: atendai/evolution-api:v1.8.2
    container_name: salon-waha
    restart: always
    ports:
      - "3006:8080"
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    environment:
      - SERVER_URL=http://localhost:8080
      - DOCKER_ENV=true
      - LOG_LEVEL=ERROR
      - AUTHENTICATION_API_KEY=waha_secret_key_2024
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_EXPOSE_IN_REQ=true
    networks:
      - web-network
    deploy:
      resources:
        limits:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  evolution_instances:
  evolution_store:

networks:
  web-network:
    driver: bridge

