services:
  db:
    image: postgres:15-alpine
    container_name: salon-db
    restart: always
    environment:
      POSTGRES_USER: salonuser
      POSTGRES_PASSWORD: salonpassword
      POSTGRES_DB: salondb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web-network
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    image: ghcr.io/croiser/sallom:latest
    container_name: salon-app
    restart: always
    ports:
      - "3005:3000"
    environment:
      DATABASE_URL: "postgresql://salonuser:salonpassword@db:5432/salondb?schema=public"
      JWT_SECRET: "sua_chave_secreta_aqui"
      WAHA_API_URL: "http://waha:3000"
      WAHA_API_KEY: "waha_secret_key_2024"
      NODE_ENV: production
      ASAAS_API_KEY: ${ASAAS_API_KEY}
      ASAAS_API_URL: ${ASAAS_API_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
    depends_on:
      - db
      - waha
    networks:
      - web-network
    deploy:
      resources:
        limits:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  waha:
    image: devlikeapro/waha
    container_name: salon-waha
    restart: always
    ports:
      - "3006:3000"
    environment:
      WHATSAPP_DEFAULT_SESSION: default
      WAHA_PRINT_QR: "true"
      WAHA_API_KEY: waha_secret_key_2024
    networks:
      - web-network
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  web-network:
    driver: bridge

