ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "cancellationDate" TIMESTAMP(3);
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "cancellationReason" TEXT;
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "checkInAt" TIMESTAMP(3);
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "comboId" TEXT;
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "endTime" TIMESTAMP(3);
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "finishedAt" TIMESTAMP(3);
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "noShow" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "recurrenceGroupId" TEXT;
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "startTime" TIMESTAMP(3);
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "totalDurationMin" INTEGER;
ALTER TABLE "staff" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "staff" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'Livre';
CREATE TABLE IF NOT EXISTS "recurrence_groups" ("id" TEXT NOT NULL, "ownerUid" TEXT NOT NULL, "staffId" TEXT, "frequency" TEXT NOT NULL, "dayOfWeek" INTEGER NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3) NOT NULL, "startTime" TEXT NOT NULL, "serviceId" TEXT, "comboId" TEXT, "status" TEXT NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "recurrence_groups_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "service_combos" ("id" TEXT NOT NULL, "ownerUid" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "price" DOUBLE PRECISION, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "service_combos_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "combo_items" ("id" TEXT NOT NULL, "comboId" TEXT NOT NULL, "serviceId" TEXT NOT NULL, "order" INTEGER NOT NULL, CONSTRAINT "combo_items_pkey" PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "recurrence_groups_ownerUid_idx" ON "recurrence_groups"("ownerUid");
CREATE INDEX IF NOT EXISTS "recurrence_groups_staffId_idx" ON "recurrence_groups"("staffId");
CREATE INDEX IF NOT EXISTS "service_combos_ownerUid_idx" ON "service_combos"("ownerUid");
CREATE INDEX IF NOT EXISTS "appointments_staffId_startTime_endTime_idx" ON "appointments"("staffId", "startTime", "endTime");
CREATE INDEX IF NOT EXISTS "appointments_ownerUid_startTime_idx" ON "appointments"("ownerUid", "startTime");
CREATE INDEX IF NOT EXISTS "appointments_recurrenceGroupId_idx" ON "appointments"("recurrenceGroupId");